config/routes.rb
Rails.application.routes.draw do
  root to: 'subscriptions#index'
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: [:show, :edit] do
    collection do
      get 'thanks'
    end
    resources :contract_cancels, only: [:index]
    resources :reviews, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'all_index'
      end
    end
    resources :subscriptions, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :contract_renewals, only: [:update]
      resources :contract_cancels, only: [:new, :create]
      resources :reviews, only: [:index, :show, :edit, :update]
    end
  end
end

app/models/contract_cancel.rb
class ContractCancel < ApplicationRecord
  # アソシエーション
  belongs_to :subscription

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :reason

  # バリデーション
  with_options presence: true do
    validates :cancel_date
    validates :reason_id
  end
  validates :reason_id, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 6,
    message: 'を選択してください'
  }
  validates :cancel_comment, length: { maximum: 300 }
end

app/controllers/contract_cancels_controller.rb
class ContractCancelsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create]
  before_action :user_identification, only: [:index, :new, :create]
  before_action :set_subs, only: [:new, :create]

  def index
    set_user
    subs = Subscription.where(user_id: params[:user_id])
    @subs = []
    @contract_cancels = []
    subs.each do |sub|
      unless sub.contract_cancel.nil?
        @subs << sub
        @contract_cancels << ContractCancel.find_by(subscription_id: sub.id)
      end
    end
  end

  def new
    set_user
    @contract_cancel = ContractCancel.new
  end

  def create
    @contract_cancel = ContractCancel.new(cancel_params)
    if @contract_cancel.save
      redirect_to user_path(current_user)
    else
      set_user
      render :new
    end
  end

  private

  def user_identification
    redirect_to user_path(current_user) if current_user != User.find_by(id: params[:user_id])
  end

  def cancel_params
    params.require(:contract_cancel).permit(
      :cancel_date, :reason_id, :cancel_comment
    ).merge(subscription_id: params[:subscription_id])
  end

  def set_user
    @user = current_user
  end

  def set_subs
    @subs = Subscription.find_by(id: params[:subscription_id])
    redirect_to user_path(current_user) if @subs.nil?
  end
end

app/helpers/contract_cancels_helper.rb
module ContractCancelsHelper
end

app/views/contract_cancels/index.html.erb
<div class="py-24">
  <div class="select_now ">
    <div class="flex flex-col text-center w-full mb-4">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-500">Cancel Subscription List</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">解約したサブスク</p>
    </div>
  </div>

  <section class="text-gray-600 body-font">
    <div class="container px-5 pt-4 mx-auto flex flex-wrap flex-col">
      <div class="flex mx-auto flex-wrap mb-3">
        <a href=<%= new_user_subscription_path(@user) %> class="sm:px-6 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 hover:bg-gray-400 hover:bg-opacity-20 hover:text-black tracking-wider rounded-t">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg><span class="text-gray-600">Add</span>
        </a>
        <a href=<%= user_path(@user) %> class="sm:px-6 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 hover:bg-gray-400 hover:bg-opacity-20 hover:text-yellow-500 tracking-wider">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
          </svg><span class="text-gray-600">Lists</span>
        </a>
        <a href=<%= all_index_user_reviews_path(@user) %> class="sm:px-4 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 hover:bg-gray-400 hover:bg-opacity-20 hover:text-pink-400 tracking-wider">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
          </svg><span class="text-gray-600">Reviews</span>
        </a>
        <a class="sm:px-4 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 bg-gray-300 bg-opacity-40 text-gray-500 tracking-wider">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
          </svg>Cancels
        </a>
      </div>
    </div> 
  </section>

  <% if @subs.length == 0 %>
    <div class="mt-2 text-center text-gray-500" >解約状態にしたサブスクは、まだありません。</div>
  <% else %>
    <section class="text-gray-600 body-font">
      <div class="container px-5 py-2 mx-auto">
        <div class="flex flex-wrap -m-2">
          <% @subs.zip(@contract_cancels) do |sub, cancel| %>
            <div class="p-2 xl:w-1/3 lg:w-1/2 md:w-1/2 w-full">
              <a href=<%=user_subscription_path(@user, sub)%>>
                <div class="h-full flex items-center border-blue-200 border-2 p-4 rounded-lg hover:border-blue-400">
                <div class="mr-4 w-16 h-16 inline-flex items-center justify-center rounded-full bg-gray-100 text-blue-500 flex-shrink-0">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
                  </svg>
                </div>
                  <div class="flex-grow">
                    <h2 class="text-gray-900 title-font font-medium"><%= sub.name %></h2>
                    <p class="text-gray-500">解約日：<%= cancel.cancel_date %></p>
                  </div>
                </div>
              </a>
            </div>
          <% end %>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/contract_cancels/new.html.erb
<div class="bg-gray-100 py-8">
  <%= form_with model: @contract_cancel, url: user_subscription_contract_cancels_path(@user, @subs), method: :POST, class:"w-full", local: true do |f| %>
    <div class="container px-5 py-6 mx-auto my-8 flex flex-col items-center lg:w-2/4 md:w-2/4 sm:w-96 bg-white rounded-lg">

      <%= render "shared/error_messages", model: f.object %>

      <div class="my-2 mx-auto">
        <h2 class="text-gray-900 text-2xl text-center font-bold title-font my-4"><%= @subs.name%>の解約</h2>
        <div class="flex-col items-center justify-center w-full mb-4">
          <div class="relative p-2 mx-auto">
             <label for="cancel_date" class="block text-gray-600">解約日</label>
              <% @contract_cancel.cancel_date = Date.today if @contract_cancel.cancel_date.nil? %>
              <%= f.date_field :cancel_date, value: @contract_cancel.cancel_date, class: "w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 resize-none transition-colors ease-in-out" %>
          </div>

          <div class="relative p-2 mx-auto">
            <label for="update_cycle" class="block text-gray-600">解約理由</label>
            <%= f.collection_select(:reason_id, Reason.all, :id, :name, {}, {class:"w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 resize-none transition-colors ease-in-out", id:"readon_id"}) %>
          </div>

          <div class="relative mt-2 p-2 mx-auto">
              <%= f.text_area :cancel_comment, id:"action_comment", placeholder:"解約のきっかけ、思考などを書き留める", size:"70x4",maxlength:"300", class: "word_count w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 leading-8" %>
              <div class="text-right pr-2">あと<span class="word_remaining" id="action_comment_length">300</span>文字</div>
          </div>

          <div class="relative p-2 mx-auto">
            <%= f.submit "解約する" ,class:"flex mx-auto text-white bg-black border-0 focus:outline-none hover:bg-gray-200 hover:text-black py-2 px-8 rounded text-lg" %>
          </div>

          <p class="mt-4 text-center text-sm text-blue-400">※実際のご解約処理は、<br class="lg:hidden">各サービスサイトでお願い致します。</p>

      </div>
    </div>
  <% end %>
</div>