config/routes.rb
Rails.application.routes.draw do
  root to: 'subscriptions#index'
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: [:show, :edit] do
    collection do
      get 'thanks'
    end
    resources :contract_cancels, only: [:index]
    resources :reviews, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'all_index'
      end
    end
    resources :subscriptions, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :contract_renewals, only: [:update]
      resources :contract_cancels, only: [:new, :create]
      resources :reviews, only: [:index, :show, :edit, :update]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password, format: {
    with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i,
    message: 'は半角英数字の混合で設定してください',
    allow_blank: true
  }
  validates :nickname, presence: true, length: { maximum: 6 }
  has_many :subscriptions, dependent: :destroy
  has_many :reviews
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit]
  before_action :user_identification, only: [:show, :edit]

  def show
    @user = User.find_by(id: params[:id])
    all_subs = Subscription.where(user_id: params[:id])
    @subs = []
    @renewal = []
    all_subs.each do |sub|
      if sub.contract_cancel.nil?
        @subs << sub
        @renewal << sub.contract_renewal
      end
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def thanks
    redirect_to user_path(current_user) if user_signed_in?
  end

  private

  def user_identification
    redirect_to user_path(current_user) if current_user != User.find_by(id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="p-4">
      <div class="h-full bg-gray-100 bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
        <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">GoodBye</h2>
        <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">退会処理</h1>
        <p class="leading-relaxed mb-2">登録したサブスクデータも全て削除されます</p>
        <p class="leading-relaxed mb-6">退会してよろしいですか？</p>
        <%= form_with url: registration_path(@user), method: :delete, class: "flex justify-center", local: true do |f| %>
          <%= f.submit '退会します', class: "p-4 text-base text-white bg-gray-500 rounded-sm hover:text-black hover:bg-gray-200" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<div class="flex justify-end text-gray-400 py-1 px-4">
  <div class="flex">
    <a href='https://forms.gle/FwRDjMCqmdw4XaPW7' class="hover:text-gray-600">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    </a>
  </div>
</div>

<div class="py-24">
  <div class="select_now ">
    <div class="flex flex-col text-center w-full mb-4">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-500">Subscription List</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">契約中のサブスク</p>
    </div>
  </div>

  <section class="text-gray-600 body-font">
    <div class="container px-5 pt-4 mx-auto flex flex-wrap flex-col">
      <div class="flex mx-auto flex-wrap mb-3">
        <a href=<%= new_user_subscription_path(@user) %> class="sm:px-6 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 hover:bg-gray-400 hover:bg-opacity-20 hover:text-black tracking-wider rounded-t">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg><span class="text-gray-600">Add</span>
        </a>
        <a href=<%= user_path(@user) %> class="sm:px-6 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 bg-gray-300 bg-opacity-40 text-gray-500 tracking-wider">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
          </svg><span class="text-gray-600">Lists</span>
        </a>
        <a href=<%= all_index_user_reviews_path(@user) %> class="sm:px-4 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 hover:bg-gray-400 hover:bg-opacity-20 hover:text-pink-400 tracking-wider">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
          </svg><span class="text-gray-600">Reviews</span>
        </a>
        <a href=<%= user_contract_cancels_path(@user) %> class="sm:px-4 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 hover:bg-gray-400 hover:bg-opacity-20 hover:text-blue-500 tracking-wider">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
          </svg><span class="text-gray-600">Cancels</span>
        </a>
      </div>
    </div> 
  </section>

   <% if @subs.length == 0 %>
    <div class="flex justify-center mt-2">
      <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
      </svg>
      <p class="text-center text-gray-500">
        <span class="text-gray-600">Add</span>  から、サブスクを登録してみましょう！
      </p>
    </div>
  <% else %>
    <section class="text-gray-600 body-font">
      <div class="container px-5 py-2 mx-auto">
        <div class="flex flex-wrap -m-2">
          <% @subs.zip(@renewal) do |sub, renew| %>
            <div class="relative p-2 xl:w-1/3 lg:w-1/2 md:w-1/2 w-full">
            <%# メニュー %>
            <div class="absolute right-1 top-3 mr-4 w-6 h-6 inline-flex items-center justify-center text-yellow-400 font-bold flex-shrink-0">
              <svg class="sub-ope-menu" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
              </svg>
            </div>
            <ul class="sub-ope-menu-lists hidden">
              <li class="px-4 py-2 border-r-2 border-gray-200"><%= link_to 'レビュー', user_subscription_reviews_path(@user, sub) %></li>
              <li class="px-4 py-2 border-r-2 border-gray-200"><%= link_to '編集', edit_user_subscription_path(@user, sub) %></li>
              <li class="px-4 py-2 border-r-2 border-gray-200">
                <%= form_with url: user_subscription_path(@user, sub), method: :delete, class: "sub-delete-form", local: true do |f| %>
                  <%= f.submit '削除', class: "delete_btn bg-gray-100" %>
                <% end %>
              </li>
              <li class="px-4 py-2"><%= link_to '解約', new_user_subscription_contract_cancel_path(@user, sub) %></li>
            </ul>
            <%# メニュー %>
            <%# 通知 %>
            <div class="update-notification hidden">
              <span class="absolute left-1.5 top-1.5 rounded-full h-4 w-4 bg-gray-300"></span>
              <span class="absolute left-1 top-1 animate-ping inline-flex h-5 w-5 rounded-full bg-gray-400 opacity-75"></span>
            </div>
            <%# 通知 %>
            <a href=<%= user_subscription_path(@user, sub) %>>
              <div class="h-full flex items-center border-yellow-100 border-2 p-4 rounded-lg  hover:border-yellow-400">
              <div class="mr-4 w-16 h-16 inline-flex items-center justify-center rounded-full bg-gray-100 text-yellow-400 flex-shrink-0">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
                </svg>
              </div>
                <div class="flex-grow">
                  <h2 class="text-gray-900 title-font font-medium"><%= sub.name %></h2>
                  <div class="next_update_info">次回更新日：<span class="m-sub-update-date text-gray-500"><%= renew.next_update_date %></span></div>
                  <div class="m-sub-update-link hidden">
                    <%= form_with url: user_subscription_contract_renewal_path(@user, sub, renew), method: :PATCH, class: "sub-update-form", local: true do |f| %>
                      <%= f.submit 'Clickで更新', class: "m-sub-update-link_tag animate-bounce mt-5 text-gray-400 text-lg font-bold bg-white bg-opacity-0 hover:text-gray-700" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </a>
            </div>
          <% end %>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/users/thanks.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="p-4">
      <div class="h-full bg-gray-100 bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
        <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">ThankYou</h2>
        <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">退会完了</h1>
        <p class="leading-relaxed mb-1">ユーザー情報を削除しました</p>
        <p class="leading-relaxed mb-8">ご利用ありがとうございました！</p>
        <%= link_to 'アンケート', 'https://forms.gle/T66dtCYhbGbaXKiaA', class: "mt-4 text-base text-blue-400 bg-white bg-opacity-0 hover:text-blue-600" %>
        <p class="leading-relaxed mb-1">よろしければ、ご回答をお願いします</p>
        <p class="leading-relaxed mb-1">(Googleフォームに遷移します)</p>
      </div>
    </div>
  </div>
</section>