config/routes.rb
Rails.application.routes.draw do
  root to: 'subscriptions#index'
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: [:show, :edit] do
    collection do
      get 'thanks'
    end
    resources :contract_cancels, only: [:index]
    resources :reviews, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'all_index'
      end
    end
    resources :subscriptions, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :contract_renewals, only: [:update]
      resources :contract_cancels, only: [:new, :create]
      resources :reviews, only: [:index, :show, :edit, :update]
    end
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  # バリデーション
  with_options presence: true do
    validates :name, length: { maximum: 10 }
    validates :price, numericality: {
      only_integer: true,
      greater_than_or_equal_to: 0,
      message: 'は0以上の整数を入力してください'
    }
    validates :contract_date
    validates :update_cycle, numericality: {
      only_integer: true,
      greater_than_or_equal_to: 1,
      less_than_or_equal_to: 31,
      allow_blank: true
    }
  end

  validates :update_type_id, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 3,
    message: 'は日・月・年のいずれかを選択してください'
  }

  validates :update_day_type_id, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 2
  }, unless: :type_is_day

  # アソシエーション
  belongs_to :user
  has_one :contract_renewal, dependent: :destroy
  has_one :contract_cancel, dependent: :destroy
  has_many :reviews, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :update_type
  belongs_to :update_day_type

  # メソッド
  def type_is_day
    update_type_id == 1
  end

  def get_update_cycle_days(update_date)
    case update_type_id
    when 1 # 日
      update_date - update_cycle
    when 2 # 月
      update_cycle.times do
        update_date = update_date.last_month
      end
      update_date
    when 3 # 年
      update_cycle.times do
        update_date = update_date.last_year
      end
      update_date
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :user_identification, except: [:index]
  before_action :set_subs, only: [:show, :edit, :update, :destroy]
  before_action :set_renewal, only: [:show]

  def show
    set_user
    # サブスク・アクションプラン評価の平均を取得
    reviews = @subs.reviews.includes(:action_plan)
    @review_ave = Review.get_review_rate_ave(reviews)
    @action_ave = ActionPlan.get_action_rate_ave(reviews)
    # 解約済であればcontract_cancelのレコードを取得
    @contract_cancel = ContractCancel.find_by(subscription_id: @subs.id) unless @subs.contract_cancel.nil?
  end

  def new
    set_user
    @subs = Subscription.new
  end

  def create
    # @sub・@renewal、どちらのsaveも成功した際のみレコードが保存される
    ActiveRecord::Base.transaction do
      @subs = Subscription.new(subs_params)
      # 更新タイプが「日」なら、更新日タイプをnilにする
      @subs.update_day_type_id = nil if @subs.update_type_id == 1
      @subs.save!
      # 契約更新テーブルに反映
      first_renewal(@subs.id)
    end
    # @sub・@renewal、どちらのsaveも成功したらマイページに遷移する
    redirect_to user_path(current_user)
    #  @sub・@renewal、いずれかのsaveに失敗すれば、登録ページにrenderされ、エラーメッセージが表示される
    rescue => e
      set_user
      render :new
  end

  def edit
    set_user
  end

  def update
    update_sub = subs_params
    # 更新タイプが「日」なら、更新日タイプをnilにする
    update_sub[:update_day_type_id] = nil if update_sub[:update_type_id] == '1'
    if @subs.update(subs_params)
      render json: { process_ng: false }
    else
      set_user
      error_messages = @subs.errors.full_messages
      render json: { process_ng: true, error_messages: error_messages }
    end
  end

  def destroy
    sub_name = @subs.name
    if @subs.destroy
      render json: { subname: sub_name }
    else
      render json: { process_ng: true }
    end
  end

  private

  # ログインユーザーの確認
  def user_identification
    redirect_to user_path(current_user) if current_user != User.find_by(id: params[:user_id])
  end

  # Userブジェクトのセット
  def set_user
    @user = current_user
  end

  # Subscriptionオブジェクトのセット
  def set_subs
    @subs = Subscription.find_by(id: params[:id])
    redirect_to user_path(current_user) if @subs.nil?
  end

  # ContractRenewalオブジェクトのセット
  def set_renewal
    @renewal = ContractRenewal.find_by(subscription_id: @subs.id)
    redirect_to user_path(current_user) if @renewal.nil?
  end

  # Subscriptionストロングパラメーター
  def subs_params
    params.require(:subscription).permit(
      :name, :price, :contract_date, :update_type_id, :update_cycle, :update_day_type_id
    ).merge(user_id: current_user.id)
  end

  #  サブスク「登録」時、契約更新テーブルにも反映
  def first_renewal(sub_id)
    @subs = Subscription.find_by(id: sub_id)
    @renewal = ContractRenewal.new(
      renewal_count: 0,
      total_price: @subs.price,
      update_date: Date.today,
      subscription_id: @subs.id
    )
    @renewal.next_update_date = @renewal.get_update_date(@subs, @subs.contract_date)
    @renewal.total_period = @renewal.get_total_period(@subs.contract_date, @renewal.next_update_date)

    judge = true

    # 次回更新日 >= 今日の日付 になるまで、更新処理を行う
    while judge
      if @renewal.next_update_date >= Date.today
        judge = false
      else
        @renewal.update_date = @renewal.next_update_date
        @renewal.next_update_date = @renewal.get_update_date(@subs, @renewal.next_update_date)
        @renewal.renewal_count += 1
        @renewal.total_price += @subs.price
        @renewal.total_period += @renewal.get_total_period(@renewal.update_date, @renewal.next_update_date)
      end
    end

    @renewal.save!
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/edit.html.erb
<div class="bg-gray-100 py-8">
  <%= form_with model: [@user, @subs], url: user_subscription_path(@user, @subs), method: :PATCH, id: "sub-edit-form", class:"w-full", local: true do |f| %>
    <div class="container px-5 py-6 mx-auto my-8 flex flex-col items-center lg:w-2/4 md:w-2/4 sm:w-96 bg-white rounded-lg">
      <h2 id="sub_edit_title" class="text-gray-900 text-2xl font-bold title-font my-5">サブスク編集</h2>

      <div class="my-2 mx-auto">

          <div class="relative p-2 w-10/12 mx-auto">
              <label for="name" class="block text-gray-600">サブスク名</label>
              <%= f.text_field :name, id:"name", placeholder:"10文字以内" ,maxlength:"10", class: "w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
          </div>

          <div class="relative p-2 w-10/12 mx-auto">
              <label for="price" class="block text-gray-600">価格</label>
              <%= f.number_field :price, class:"", id:"price", placeholder:"数字のみOK", class: "w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
          </div>

          <div class="relative p-2 w-10/12 mx-auto">
              <label for="update_cycle" class="block text-gray-600">更新サイクル</label>
              <%= f.number_field :update_cycle, id:"update_cycle", placeholder:"数値のみOK", class:"w-6/12 focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out" %>
              <%= f.collection_radio_buttons(:update_type_id, UpdateType.all, :id, :name, {}, {class:"mr-px ml-2 focus:border-gray-400 focus:ring-2 focus:ring-gray-400", id:"update_type_id"}) %>
          </div>

          <div class="hidden" id="day_type_btn" >
              <label for="update_day_type_id" class="block text-gray-600 mb-2">更新日のタイプ</label>
              <%= f.check_box(:update_day_type_id, {class:"form-checkbox h-4 w-4"}, 1, 2) %>
              <span class="ml-2">1日更新ならチェック</span>
          </div>

          <div class="test relative mt-2 p-2 w-10/12 mx-auto">
            <%= f.submit "更新する" ,id: 'sub-edit-btn', class:"flex mx-auto text-white bg-black border-0 focus:outline-none hover:bg-gray-200 hover:text-black py-2 px-8 rounded text-lg" %>
          </div>

          <div class="relative mt-2 p-2 w-10/12 mx-auto text-center">
            <%= link_to '＊契約日を変更したいとき(仮)', '#', class: 'text-sm text-blue-400 hover:bg-gray-200' %>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/subscriptions/index.html.erb
<header class="text-black body-font bg-white" id="header">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <div class="flex flex-col justify-center title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <div>
        <%= link_to 'Look Back', root_path, class: "text-2xl text-black font-bold" %>
      </div>
      <div class="text-xs">振り返る サブスク管理</div>
    </div>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <% if user_signed_in? %>
        <span class="mr-5 text-black flex">
        <%=link_to 'My page', user_path(current_user), id: "my-page", class: "pr-1" %> <%#current_user.nicknameさん%>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
        </svg>
        </span>
        <%= link_to 'Logout' , destroy_user_session_path, method: :delete, class: "hover:bg-gray-200 hover:text-black  w-22 py-2 pr-1 rounded" %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
        </svg>
      <% else %>
        <%= link_to 'Sign up', new_user_registration_path, class: "hover:bg-gray-200 hover:text-black w-22 py-2 px-2 rounded mr-5" %>
        <%= link_to 'Login', new_user_session_path, class: "hover:bg-gray-200 hover:text-black w-22 py-2 px-2 rounded mr-5" %>
      <% end %>
    </nav>
  </div>
</header>

<div class="bg">
  <div class="flex justify-center">
    <%= image_tag 'top_logo.png', class: "py-12 w-1/2 max-w-lg md:py-20 lg:py-32"%>
  </div>
</div>

<footer class="bg-white" id="footer">
  <div class="">
      <div class="container mx-auto py-4 px-5 flex flex-wrap flex-col sm:flex-row">
        <p class="text-black text-sm text-center sm:text-left">© 2020 Tailblocks —
          <a href="https://twitter.com/knyttneve" rel="noopener noreferrer" class="text-black ml-1" target="_blank">@knyttneve</a>
        </p>
        <span class="inline-flex sm:ml-auto sm:mt-0 mt-2 justify-center sm:justify-start">
          <a class="text-black">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
            </svg>
          </a>
          <a class="ml-3 text-black">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
            </svg>
          </a>
          <a class="ml-3 text-black">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
              <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
            </svg>
          </a>
          <a class="ml-3 text-black">
            <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
              <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
              <circle cx="4" cy="4" r="2" stroke="none"></circle>
            </svg>
          </a>
        </span>
      </div>
    </div>
</footer>

app/views/subscriptions/new.html.erb
<div class="bg-gray-100 py-8">
  <%= form_with model: [@user, @subs], url: user_subscriptions_path(@user), method: :POST, class:"w-full", local: true do |f| %>
    <div class="container px-5 py-6 mx-auto my-8 flex flex-col items-center lg:w-2/4 md:w-2/4 sm:w-96 bg-white rounded-lg">
      <h2 class="text-gray-900 text-2xl font-bold title-font my-5">サブスク登録</h2>

      <%= render "shared/error_messages", model: f.object %>
      <%= render "shared/error_messages_second", model: @renewal if @renewal != nil %>

      <div class="my-2 mx-auto">

          <div class="relative p-2 w-10/12 mx-auto">
              <label for="name" class="block text-gray-600">サブスク名</label>
              <%= f.text_field :name, id:"name", placeholder:"10文字以内" ,maxlength:"10", class: "w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
          </div>

          <div class="relative p-2 w-10/12 mx-auto">
              <label for="price" class="block text-gray-600">価格</label>
              <%= f.number_field :price, class:"", id:"price", placeholder:"数字のみOK", class: "w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
          </div>

          <%# render時に、入力内容を保持する %>
          <% @subs.contract_date = Date.today if @subs.contract_date.nil? %>
          <div class="relative p-2 w-10/12 mx-auto">
              <label for="contract_date" class="block text-gray-600">契約開始日</label>
              <%= f.date_field :contract_date, id:"contract_date", value: @subs.contract_date, class: "w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 resize-none transition-colors ease-in-out" %>
          </div>

          <div class="relative p-2 w-10/12 mx-auto">
              <label for="update_cycle" class="block text-gray-600">更新サイクル</label>
              <%= f.number_field :update_cycle, id:"update_cycle", placeholder:"数値のみOK", class:"w-6/12 focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out" %>
              <%= f.collection_radio_buttons(:update_type_id, UpdateType.all, :id, :name, {}, {class:"mr-px ml-2 focus:border-gray-400 focus:ring-2 focus:ring-gray-400", id:"update_type_id"}) %>
          </div>

          <div class="hidden" id="day_type_btn" >
              <label for="update_day_type_id" class="block text-gray-600 mb-2">更新日のタイプ</label>
              <%= f.check_box(:update_day_type_id, {class:"form-checkbox h-4 w-4"}, 1, 2) %>
              <span class="ml-2">1日更新ならチェック</span>
          </div>

          <div class="relative mt-2 p-2 w-10/12 mx-auto">
            <%= f.submit "登録する" ,class:"flex mx-auto text-white bg-black border-0 focus:outline-none hover:bg-gray-200 hover:text-black py-2 px-8 rounded text-lg" %>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/subscriptions/show.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="text-center mb-20">
      <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900 mb-4"><%= @subs.name %></h1>
      <div class="flex mt-6 justify-center">
        <div class="w-32 h-1 rounded-full bg-yellow-400 inline-flex"></div>
      </div>
      <div class="flex flex-col mt-6 justify-center">
      <% unless @contract_cancel.nil? %>
        <h2 class="text-xl text-gray-90"><%= @contract_cancel.cancel_date %>：解約済</h2>
        <div class="pt-2">解約理由：<%= @contract_cancel.reason.name %></div>
        <div class="pt-2">詳細：<%= @contract_cancel.cancel_comment %></div>
      <% end %>
      </div>
    </div>
    <div class="flex flex-wrap justify-center sm:-m-4 -mx-4 -mb-10 -mt-4 md:space-y-0 space-y-6">
      <div class="p-4 md:w-1/3 flex flex-col text-center items-center">
        <div class="w-20 h-20 inline-flex items-center justify-center rounded-full bg-gray-100 text-yellow-400 mb-5 flex-shrink-0">
          <svg xmlns="http://www.w3.org/2000/svg" stroke-linecap="round class="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M9 8l3 5m0 0l3-5m-3 5v4m-3-5h6m-6 3h6m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>
        <div class="w-400px flex-grow">
          <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Price</h2>
          <p class="leading-relaxed text-base">価格：<%= @subs.price %>円</p>
          <p class="leading-relaxed text-base">累計：<%= @renewal.total_price %>円投資中</p>
        </div>
      </div>
      <div class="p-4 md:w-1/3 flex flex-col text-center items-center">
        <div class="w-20 h-20 inline-flex items-center justify-center rounded-full bg-gray-100 text-yellow-400 mb-5 flex-shrink-0">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
        </div>
        <div class="w-400px flex-grow">
          <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Period</h2>
          <p class="leading-relaxed text-base">契約開始：<%= @subs.contract_date %></p>
          <p class="leading-relaxed text-base">次回更新日：<%= @renewal.next_update_date %></p>
          <p class="leading-relaxed text-base">累計<%= @renewal.total_period %>日継続中</p>
          <p class="leading-relaxed text-base">
            更新サイクル
            <%= @subs.update_cycle.to_s%>
            <%= "ヶ" if @subs.update_type.id == 2 %>
            <%= @subs.update_type.name %>
          </p>
        </div>
      </div>
      <div class="p-4 md:w-1/3 flex flex-col text-center items-center">
        <div class="w-20 h-20 inline-flex items-center justify-center rounded-full bg-gray-100 text-yellow-400 mb-5 flex-shrink-0">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
        </svg>
        </div>
        <div class="w-400px flex-grow">
          <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Review</h2>
          <div>
            <p class="leading-relaxed text-base pb-1">サブスクAve</p>
            <div data-score=<%= @review_ave %><%if @review_ave.nil? %>0<% end %> class="average_rate_read_only flex justify-center"></div>
            <% if @review_ave.nil? %>
              <p>まだ評価がありません</p> 
            <% end %>
          </div>
          <div>
            <p class="leading-relaxed text-base pb-1">アクションAve</p>
            <div data-score=<%= @action_ave %><%if @action_ave.nil? %>0<% end %> class="average_rate_read_only flex justify-center""></div>
            <% if @action_ave.nil? %>
              <p>まだ評価がありません</p> 
            <% end %>
          </div>
          <a class="mt-3 text-gray-500 hover:text-black inline-flex items-center" href=<%= user_subscription_reviews_path(@user, @subs) %>>Look More
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="animate-pulse w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </div>
    </div>
    <div class="flex justify-around mt-16">
    <% if @contract_cancel.nil? %>
      <%= link_to '編集する', edit_user_subscription_path(@user, @subs), class: "text-white bg-yellow-500 bg-opacity-70 border-0 py-2 px-8 focus:outline-none hover:bg-yellow-500 hover:bg-opacity-90 rounded text-lg" %>
    <% end %>
      <%= form_with url: user_subscription_path(@user, @subs), method: :delete, id: "sub-delete-form", local: true do |f| %>
        <%= f.submit '削除する', id: "sub-show-delete-btn", class: "block text-white bg-yellow-500 bg-opacity-70 border-0 py-2 px-8 focus:outline-none hover:bg-yellow-500 hover:bg-opacity-90 rounded text-lg" %>
      <% end %>
    </div>
  </div>
</section>