config/routes.rb
Rails.application.routes.draw do
  root to: 'subscriptions#index'
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: [:show, :edit] do
    collection do
      get 'thanks'
    end
    resources :contract_cancels, only: [:index]
    resources :reviews, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
      collection do
        get 'all_index'
      end
    end
    resources :subscriptions, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :contract_renewals, only: [:update]
      resources :contract_cancels, only: [:new, :create]
      resources :reviews, only: [:index, :show, :edit, :update]
    end
  end
end

app/models/review_action.rb
class ReviewAction
  # フォームオブジェクトで扱う属性
  include ActiveModel::Model
  attr_accessor :review_rate,
                :review_comment,
                :start_date,
                :end_date,
                :later_check_id,
                :user_id,
                :subscription_id,
                :action_rate,
                :action_review_comment,
                :action_plan,
                :review_id

  # Reviewモデルバリデーション
  with_options presence: true do
    validates :start_date
    validates :end_date
    validates :later_check_id, numericality: {
      only_integer: true,
      greater_than_or_equal_to: 1,
      less_than_or_equal_to: 2
    }
    validates :user_id
    validates :subscription_id
  end

  validates :review_comment, length: { maximum: 300 }

  validates :review_rate, presence: {
    message: 'レビューを選択してください'
  }, unless: :type_is_later
  validates :review_rate, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
    message: 'レビューを選択してください',
    allow_blank: true
  }, unless: :type_is_later

  # ActionPlanモデルバリデーション
  validates :action_plan, length: { maximum: 300 }
  validates :action_review_comment, length: { maximum: 300 }

  validates :action_rate, presence: {
    message: 'レビューを選択してください'
  }, unless: :type_is_later
  validates :action_rate, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
    message: 'レビューを選択してください',
    allow_blank: true
  }, unless: :type_is_later

  validates :action_plan, presence: true, unless: :type_is_later
  validates :review_id, presence: true

  # メソッド
  def type_is_later
    later_check_id == '2'
  end

  def save
    review = Review.create!(
      review_rate: review_rate,
      review_comment: review_comment,
      start_date: start_date,
      end_date: end_date,
      later_check_id: later_check_id,
      user_id: user_id,
      subscription_id: subscription_id
    )
    ActionPlan.create!(
      action_rate: action_rate,
      action_review_comment: action_review_comment,
      action_plan: action_plan,
      review_id: review.id
    )
  end

  def update
    review = Review.find_by(id: review_id)
    review.update!(
      review_rate: review_rate,
      review_comment: review_comment,
      start_date: start_date,
      end_date: end_date,
      later_check_id: later_check_id,
      user_id: user_id,
      subscription_id: subscription_id
    )

    action = ActionPlan.find_by(review_id: review_id)
    action.update!(
      action_rate: action_rate,
      action_review_comment: action_review_comment,
      action_plan: action_plan,
      review_id: review_id
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:all_index, :index, :show, :edit, :update]
  before_action :user_identification, only: [:all_index, :index, :show, :edit, :update]
  before_action :set_user, only: [:all_index, :index, :show, :edit]
  before_action :set_subs, only: [:index, :show, :edit]
  before_action :set_review, only: [:show, :edit]
  before_action :set_action, only: [:show, :edit]
  before_action :check_params_ids, only: [:update]

  def all_index
    @subs = Subscription.where(user_id: @user.id)
    all_reviews = Review.where(user_id: @user.id).includes(:action_plan).order('created_at DESC')

    @reviews = []
    all_reviews.each do |review|
      @reviews << review if review.later_check_id == 2
    end
  end

  def index
    @reviews = Review.where(subscription_id: params[:subscription_id]).includes(:action_plan).order('created_at DESC')
    @un_reviews = Review.un_review_exit(@user)
  end

  def show
  end

  def edit
    @review_action = ReviewAction.new(
      review_rate: @review.review_rate,
      review_comment: @review.review_comment,
      start_date: @review.start_date,
      end_date: @review.end_date,
      later_check_id: @review.later_check_id,
      subscription_id: @review.subscription_id,
      action_rate: @action.action_rate,
      action_review_comment: @action.action_review_comment,
      action_plan: @action.action_plan,
      review_id: @action.review_id
    )
  end

  def update
    @review_action = ReviewAction.new(review_params)
    ActiveRecord::Base.transaction do
      @review_action.valid?
      @review_action.update
    end
    redirect_to user_subscription_reviews_path(current_user, params[:subscription_id])
    rescue => e
      set_user
      set_subs
      set_review
      render :edit
  end

  private

  # ログインユーザーの確認
  def user_identification
    redirect_to user_path(current_user) if current_user != User.find_by(id: params[:user_id])
  end

  # ReviewActionストロングパラメーター
  def review_params
    params.require(:review_action).permit(
      :review_rate, :review_comment, :start_date, :end_date, :later_check_id,
      :action_rate, :action_review_comment, :action_plan
    ).merge(user_id: params[:user_id], subscription_id: params[:subscription_id], review_id: params[:id])
  end

  # Userブジェクトのセット
  def set_user
    @user = current_user
  end

  # Subscriptionオブジェクトのセット
  def set_subs
    @subs = Subscription.find_by(id: params[:subscription_id])
    redirect_to user_path(current_user) if @subs.nil?
  end

  def set_review
    @review = Review.find_by(id: params[:id])
    redirect_to user_path(current_user) if @review.nil?
  end

  def set_action
    @action = ActionPlan.find_by(review_id: params[:id])
    redirect_to user_path(current_user) if @action.nil?
  end

  def check_params_ids
    subs = Subscription.find_by(id: params[:subscription_id])
    review = Review.find_by(id: params[:id])
    redirect_to user_path(current_user) if subs.nil? || review.nil?
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/all_index.html.erb
<div class="my-24">
  <div class="select_now ">
    <div class="flex flex-col text-center w-full mb-4">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-500">Wating Review List</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">振り返り待ち</p>
    </div>
  </div>

 <section class="text-gray-600 body-font">
    <div class="container px-5 pt-4 mx-auto flex flex-wrap flex-col">
      <div class="flex mx-auto flex-wrap mb-3">
        <a href=<%= new_user_subscription_path(@user) %> class="sm:px-6 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 hover:bg-gray-400 hover:bg-opacity-20 hover:text-black tracking-wider rounded-t">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg><span class="text-gray-600">Add</span>
        </a>
        <a href=<%= user_path(@user) %> class="sm:px-6 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 hover:bg-gray-400 hover:bg-opacity-20 hover:text-yellow-500 tracking-wider">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
          </svg><span class="text-gray-600">Lists</span>
        </a>
        <a href=<%= all_index_user_reviews_path(@user) %> class="sm:px-4 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 bg-gray-300 bg-opacity-40 text-gray-500 tracking-wider">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
          </svg><span class="text-gray-600">Reviews</span>
        </a>
        <a href=<%= user_contract_cancels_path(@user) %> class="sm:px-4 py-3 w-1/2 sm:w-auto justify-center sm:justify-start border-b-2 title-font font-medium inline-flex items-center leading-none border-gray-200 hover:bg-gray-400 hover:bg-opacity-20 hover:text-blue-500 tracking-wider">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
          </svg><span class="text-gray-600">Cancels</span>
        </a>
      </div>
    </div> 
  </section>

  <% if @reviews.length == 0 %>
    <div class="mt-2 text-center text-gray-500" >評価待ちのレビューは、ありません。</div>
  <% else %>
    <section class="text-gray-600 body-font">
      <div class="container px-5 py-2 mx-auto">
        <div class="flex flex-wrap -m-2">
          <% @reviews.each do |review| %>
            <div class="p-2 xl:w-1/3 lg:w-1/2 md:w-1/2  w-full">
              <a href=<%= edit_user_subscription_review_path(@user, review.subscription, review) %>>
                <div class="h-full flex items-center border-pink-100 border-2 p-4 rounded-lg  hover:border-pink-400">
                <div class="mr-4 w-16 h-16 inline-flex items-center justify-center rounded-full bg-gray-100 text-pink-400 flex-shrink-0">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                  </svg>
                </div>
                  <div class="flex-grow">
                    <h2 class="text-gray-900 title-font font-medium"><%= review.subscription.name %></h2>
                    <p class="text-gray-500"><%= review.start_date %> ~ <%= review.end_date %></p>
                  </div>
                </div>
              </a>
            </div>
          <% end %>
        </div>
      </div>
    </section>
   <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="bg-gray-100 py-8">
  <%= form_with model: [@review_action], url: user_subscription_review_path(@user, @subs, @review), method: :PATCH, class:"w-full", id: "new_review_form", local: true do |f| %>
    <div class="container px-5 py-6 mx-auto my-8 flex flex-col items-center lg:w-2/4 md:w-2/4 sm:w-96 bg-white rounded-lg">

      <%= render "shared/error_messages", model: f.object %>

      <div class="my-2 mx-auto">
        <h2 class="text-gray-900 text-2xl text-center font-bold title-font my-4"><%= @subs.name%>の振り返り</h2>
        <h4 class="text-gray-500 text-lg text-center font-bold title-font mb-8"><%= @review_action.start_date %> 〜 <%= @review_action.end_date %></h2>
        
        <div class="flex items-center justify-center w-full mb-4">
          <label class="flex items-center cursor-pointer">
            <div class="relative">
              <input type="hidden" value="1" name="review_action[later_check_id]" >
              <input class="sr-only" type="checkbox" value="2" name="review_action[later_check_id]"  id="review_action_later_check_id">
              <div class="w-10 h-4 bg-gray-300 rounded-full shadow-inner"></div>
              <div class="dot absolute w-6 h-6 bg-black rounded-full shadow -left-1 -top-1 transition"></div>
            </div>
            <div class="ml-3 text-gray-700 font-medium">
              あとで振り返る
            </div>
          </label>
        </div>
        <div class="hidden" id="later_check_warning">入力内容は、一時保存されます</div>


        <div class="py-6" id="later_hidden_parts">
          <h2 class="bubble relative text-gray-700 font-medium text-center bg-blue-100 rounded-lg w-52 p-2 mx-auto my-4">サブスクは☆いくつ？</h2>
          <div data-score=<%= @review_action.review_rate %><% if @review_action.review_rate.nil? || @review_action.review_rate == '' %>0<% end %> class="flex justify-center py-4" id="review_rate"></div>
          <div class="relative p-2 mx-auto">
              <%= f.text_area :review_comment, id:"review_comment", placeholder:"今回のサブスクコンテンツは、いかがでしたか？\n感じたことを書き出して見ましょう！", size: "70x4",maxlength:300, class: "word_count w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 leading-8" %>
          </div>
          <div class="text-right pr-2">あと<span class="word_remaining">300</span>文字</div>

          <h2 class="bubble relative text-gray-700 font-medium text-center bg-blue-100 rounded-lg w-52 p-2 mx-auto my-4">活用度は☆いくつ？</h2>
          <div data-score=<%= @review_action.action_rate %><% if @review_action.action_rate.nil? || @review_action.action_rate == '' %>0<% end %> class="flex justify-center py-4" id="action_rate"></div>
          <div class="relative p-2 mx-auto">
              <%= f.text_area :action_review_comment, id:"action_comment", placeholder:"実践したアクションプランを振り返ってみましょう！\n何に活用できたか、どんな行動ができたか、思い出してみましょう。", size: "70x4",maxlength:300, class: "word_count w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 leading-8" %>
          </div>
          <div class="text-right pr-2">あと<span class="word_remaining" id="action_comment_length">300</span>文字</div>

          <h2 class="bubble relative text-gray-700 font-medium text-center bg-blue-100 rounded-lg w-52 p-2 mx-auto my-6">今回は何を実践する？</h2>
          <div class="relative p-2 mx-auto">
              <%= f.text_area :action_plan, id:"action_plan", placeholder:"次回更新日までのアクションプランを設定しましょう！", size: "70x4",maxlength:300, class: "word_count w-full focus:border-gray-400 focus:ring-2 focus:ring-gray-400 bg-gray-100 bg-opacity-50 rounded border border-gray-300 text-base outline-none text-gray-700 py-1 px-3 leading-8" %>
          </div>
          <div class="text-right pr-2">あと<span class="word_remaining">300</span>文字</div>
        </div>

        <%= f.date_field :start_date, class:"hidden", value: @review_action.start_date %>
        <%= f.date_field :end_date, class:"hidden", value: @review_action.end_date %>

        <div class="relative mt-2 p-2 mx-auto">
          <%= f.submit "レビュー" ,class:"flex mx-auto text-white bg-black border-0 focus:outline-none hover:bg-gray-200 hover:text-black py-2 px-8 rounded text-lg" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/index.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h2 class="text-xs text-pink-400 tracking-widest font-medium title-font mb-1 mr-8">Look Back Data</h2>
      <div class="flex justify-center">
        <div>
          <%= link_to @subs.name, user_subscription_path(@user, @subs), class: "sm:text-3xl text-2xl text-gray-600 hover:bg-gray-400 hover:bg-opacity-20" %>
        </div>
        <%# 未レビューサブスクがあれば、未レビュー一覧へのリンクを表示する %>
        <% if @un_reviews %>
          <div class="animate-bounce ml-6">
            <div class="bubble_index hidden" id="bubble_message">
              <span class="bubble_word w-32 rounded-lg text-sm">レビュー待ち</span>
            </div>
            <a href=<%= all_index_user_reviews_path(@user) %> id="un_reviews_link" class="sm:px-4 pt-3 pb-3 sm:w-auto justify-center sm:justify-start title-font font-medium inline-flex items-center hover:bg-gray-400 hover:bg-opacity-20 text-pink-400 rounded-xl">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
              </svg>
            </a>
          </div>
        <% end %>
        <%# 未レビューサブスクがあれば、未レビュー一覧へのリンクを表示する %>
      </div>
    </div>
    <div class="flex flex-wrap -m-4">
    <% @reviews.each do |review| %>
      <div class="relative p-4 md:w-1/2 lg:w-1/3 w-full">
      <% if review.later_check.id == 2 %>
        <span class="absolute left-3 top-3 rounded-full h-4 w-4 bg-pink-300"></span>
        <span class="absolute left-2.5 top-2.5 animate-ping inline-flex h-5 w-5 rounded-full bg-pink-400 opacity-75"></span>
      <% end %>
        <div class="flex rounded-lg h-full bg-gray-100 bg-opacity-90 p-8 flex-col">
          <div class="flex items-center mb-3">
            <div class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-pink-300 text-white flex-shrink-0">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
              </svg>
            </div>
            <h2 class="text-gray-600 text-xl title-font font-medium"><%= review.start_date %> ~ <%= review.end_date %></h2>
          </div>
          <div class="flex-grow"> 
            <span class="leading-relaxed text-base font-bold border-b-2 border-gray-400">Action Plan</span>
            <p class="leading-relaxed text-base"><%= review.action_plan.action_plan.truncate(30) %></p>
            <a href= <%=  user_subscription_review_path(@user, review. subscription_id, review.id) %>  class="mt-3 text-pink-400 inline-flex items-center">Look More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</section>

app/views/reviews/show.html.erb
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex justify-center ">
      <div class="lg:w-3/4 w-full lg:px-10 lg:py-10 mt-6 lg:mt-0">

        <h2 class="text-base title-font text-gray-500 tracking-widest"><%= @subs.name %></h2>
        <div class="flex items-center">
          <h1 class="text-gray-900 mr-4 text-2xl sm:text-3xl title-font font-medium"><%= @review.start_date %> ~ <%= @review.end_date %></h1>
          <a href=<%= edit_user_subscription_review_path(@user, @subs, @review) %>>
            <button class="flex text-white bg-indigo-400 bg-opacity-75 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-500 rounded">Edit</button>
          </a>
        </div>

        <div class="my-6 items-center border-b-2 border-gray-100 ">
          <div class="flex items-center mt-4 mb-3">
            <div data-score=<%= @action.action_rate %><% if @action.action_rate.nil? %>0<% end %> class="flex justify-start" id="action_rate_read_only"></div>
            <div class="text-gray-600 ml-3">Action Plan</div>
          </div>
          <div class="my-2">
            <div class="font-bold">Plan</div>
            <div class="leading-relaxed">
              <%= simple_format(h(@action.action_plan))%>
              <% if @action.action_plan.empty? %><p class="text-gray-400">アクションプランが未入力です<br>Editボタンから、評価を入力できます</p><% end %>
            </div>
          </div>
          <div class="mb-6">
            <div class="font-bold">Look Back</div>
            <div class="leading-relaxed">
              <%= simple_format(h(@action.action_review_comment))%>
              <% if @action.action_review_comment.empty? %><p class="text-gray-400">行動の振り返りが未入力です<br>Editボタンから、評価を入力できます</p><% end %>
            </div>
          </div>
        </div>

        <div class="my-6 items-center">
          <div class="flex items-center mt-4 mb-3">
            <div data-score=<%= @review.review_rate %><% if @review.review_rate.nil? %>0<% end %> class="flex justify-start" id="review_rate_read_only"></div>
            <div class="text-gray-600 ml-3">Subscription</div>
          </div>
          <div class="my-2">
            <div class="font-bold">Review</div>
            <div class="leading-relaxed">
              <%= simple_format(h(@review.review_comment))%>
              <% if @review.review_comment.empty? %><p class="text-gray-400">レビューが未入力です<br>Editボタンから、評価を入力できます</p><% end %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>